### ISSUE TITLE
Errors in Unity 2018.1.0b13

### ISSUE THREAD

**Issue by igame3dbill** [CiaccoDavide/Alchemy-Circles-Generator#2]
setSeed is missing, did you mean plantSeed?
TextureDraw is not recognized, is there another function?
There's a 3rd part asset called TextureDraw for $5 on the asset store.
The way your commands are written, TextureDraw.drawCircle, I think maybe you are using that?

**Comment by CiaccoDavide** [comment]
https://github.com/CiaccoDavide/Alchemy-Circles-Generator/blob/master/src_Unity3D/TextureDraw.cs

I just added the missing script (there is no third party paid asset, the class names are just the same)

This was an old project...let me know if I forgot somthing else! ;)
